language: node_js

node_js:
  "lts/*"

cache: npm

script:
  - npm run lint
  - npm run spellcheck:markdown
  - npm run spellcheck:code
  - npm run spellcheck:questions
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master